services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn ecommerce_backend.wsgi:application --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: wassim_db_c3zw
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "sm-shop.onrender.com,sm-shope.netlify.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://sm-shop.onrender.com,https://sm-shope.netlify.app"