# Generated by Django 4.2.2 on 2025-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_commune_order_commune_name_order_wilaya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commune',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='commune_name',
            field=models.CharField(default='Adrar', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='wilaya_name',
            field=models.CharField(default='Adrar', max_length=100),
        ),
    ]
