# Generated by Django 4.2.2 on 2025-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_commune_alter_order_commune_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postalCode',
            field=models.CharField(default='00000', max_length=10),
        ),
    ]
