# Generated by Django 4.2.2 on 2025-04-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_postalcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postalCode',
            new_name='postal_code',
        ),
    ]
