# Generated by Django 4.2.2 on 2025-03-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Available_stock',
            field=models.IntegerField(default=0),
        ),
    ]
