# Generated by Django 4.2.2 on 2025-03-26 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
