# Generated by Django 4.2.2 on 2025-03-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_available_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Available_stock',
            new_name='AvailableStock',
        ),
    ]
