# Generated by Django 4.2.2 on 2025-03-30 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_available_stock_product_availablestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='AvailableStock',
            new_name='availableStock',
        ),
    ]
