# Generated by Django 4.2.2 on 2025-03-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_availablestock_product_availablestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availableStock',
            new_name='AvailableStock',
        ),
    ]
