# Generated by Django 4.2.2 on 2025-03-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_availablestock_product_availablestock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='AvailableStock',
            new_name='available_stock',
        ),
    ]
